import { act, cleanup, renderHook } from '@testing-library/react-native';
import { Alert, AppState } from 'react-native';
import { AppUpdateProvider, useAppUpdate } from '@/features/app-update/update-provider';
import { CHECK_INTERVAL } from '@/features/app-update/update-policy';
const mockFetch = jest.fn();
const mockStore = new Map<string, string>();
jest.mock('expo-sqlite/kv-store', () => ({ getItemSync: (key: string) => mockStore.get(key) ?? null, setItemSync: (key: string, value: string) => mockStore.set(key, value) }));
jest.mock('@/features/app-update/update-client', () => ({ fetchLatestRelease: () => mockFetch(), installedVersion: '1.0.0', updateSupport: 'apk' }));
jest.mock('expo-router', () => ({ router: { push: jest.fn() } }));
let alerts: jest.SpyInstance;
beforeEach(() => { mockStore.clear(); mockFetch.mockReset(); alerts = jest.spyOn(Alert, 'alert').mockImplementation(() => {}); });
afterEach(async () => { await cleanup(); alerts.mockRestore(); Object.defineProperty(globalThis, '__DEV__', { configurable: true, value: true }); });
test('manual retry bypasses throttle, failures never become latest, requests deduplicate', async () => {
  const { result } = await renderHook(useAppUpdate, { wrapper: AppUpdateProvider });
  let reject!: (error: Error) => void;
  mockFetch.mockReturnValueOnce(new Promise((_, fail) => { reject = fail; }));
  let pending!: Promise<void>;
  await act(() => { pending = result.current.check(); });
  await act(() => result.current.check());
  expect(mockFetch).toHaveBeenCalledTimes(1);
  await act(async () => { reject(new Error('离线')); await pending; });
  expect(result.current.state.status).toBe('error');
  mockFetch.mockResolvedValueOnce({ version: '1.2.0', notes: '说明', pageUrl: 'https://example.test' });
  await act(() => result.current.check());
  expect(result.current.state.status).toBe('available');
  expect(alerts).not.toHaveBeenCalled();
});
test('automatic foreground check persists cooldown and does not remind same release within seven days', async () => {
  Object.defineProperty(globalThis, '__DEV__', { configurable: true, value: false });
  const previousState = AppState.currentState;
  AppState.currentState = 'active';
  mockFetch.mockResolvedValue({ version: '1.2.0', notes: '', pageUrl: 'https://example.test' });
  const first = await renderHook(useAppUpdate, { wrapper: AppUpdateProvider });
  expect(mockFetch).toHaveBeenCalledTimes(1);
  expect(alerts).toHaveBeenCalledTimes(1);
  await first.unmount();
  const second = await renderHook(useAppUpdate, { wrapper: AppUpdateProvider });
  expect(mockFetch).toHaveBeenCalledTimes(1);
  await second.unmount();
  const record = JSON.parse(mockStore.get('kaku:update-check:v1')!);
  record.checked = Date.now() - CHECK_INTERVAL - 1;
  mockStore.set('kaku:update-check:v1', JSON.stringify(record));
  await renderHook(useAppUpdate, { wrapper: AppUpdateProvider });
  expect(mockFetch).toHaveBeenCalledTimes(2);
  expect(alerts).toHaveBeenCalledTimes(1);
  AppState.currentState = previousState;
});
